# Generated by Django 4.1.3 on 2022-11-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('per', models.IntegerField()),
                ('backlog', models.IntegerField()),
            ],
        ),
    ]
