# Generated by Django 4.1.3 on 2022-11-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnp', '0002_placements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='percentage',
            field=models.IntegerField(),
        ),
    ]
