# Generated by Django 4.1.3 on 2022-12-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnp', '0003_alter_studentdetails_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='placements',
            name='img',
            field=models.ImageField(null=True, upload_to='img/%y'),
        ),
    ]
