# Generated by Django 4.1.3 on 2022-12-21 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tnp', '0004_placements_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='roll_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='student_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
