# Generated by Django 4.1.3 on 2022-12-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnp', '0006_alter_studentdetails_roll_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='roll_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='student_name',
            field=models.CharField(max_length=100),
        ),
    ]
