# Generated by Django 4.1.3 on 2022-12-21 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tnp', '0007_alter_studentdetails_roll_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='user',
        ),
    ]
